// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VetGest.Data;

namespace VetGest.Migrations
{
    [DbContext(typeof(VetGestContext))]
    [Migration("20210223200315_CreacionInicial")]
    partial class CreacionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("VetGest.Models.Caso", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllazgosClinicos")
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCorporal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrecuenciaCardiaca")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrecuenciaRespiratoria")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hidratacion")
                        .HasColumnType("TEXT");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PacienteID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Peso")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RecomendacionesMedicacion")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Temperatura")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TiempoLlenadoCapilar")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("VetGest.Models.Paciente", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Chip")
                        .HasColumnType("TEXT");

                    b.Property<string>("Domicilio")
                        .HasColumnType("TEXT");

                    b.Property<string>("DueñoApellido")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("DueñoNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Especie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pelaje")
                        .HasColumnType("TEXT");

                    b.Property<string>("Raza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Telefono")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("VetGest.Models.PlanSanitario", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaRefuerzo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PacienteID")
                        .HasColumnType("TEXT");

                    b.Property<string>("VacunaAntiparasitario")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("PlanSanitarios");
                });
#pragma warning restore 612, 618
        }
    }
}
